lib/package.js

Fix for https://github.com/jspm/jspm-cli/issues/348 which currently prevents `jspm install` with 0.10.2 in certain conditions (no `endpoints.build`).

Fixes #348

---

cli.js
lib/bundle.js

As a follow up to systemjs/builder#59 released with systemjs-builder 0.6.0 this PR exposes a `--no-mangle` param for the `jspm bundle` and `jspm bundle-sfx` commands.
This allows for bundling minified but unmangled packages.
To maintain BC, mangling defaults to `true` and is only `false` if `--no-mangle` is passed.
If `--minify` is not passed, this additional option has no effect.

add --no-mangle cli param for bundle and bundle-sfx command

---

lib/bundle.js

Should really get `--highres-source-maps` into `jspm help` (along with the other cli options) too

Lowres documentation

---

package.json

This uses a temporary fork of ncp that does not do version checking. There is a [pending pull request](https://github.com/AvianFlu/ncp/issues/79) with the ncp author that has not yet been accepted.
This should temporarily fix an issue that came up while working on #410 where `jspm install` fails silently and erratically when using io.js. Eventually when the ncp PR is merged we'd want to switch back to semver.

Fixes jspm install for io.js

---

cli.js

I misunderstood the instructions for bundle and ran `jspm bundle` with nothing else, and got this error:
```
err  TypeError: Cannot call method 'split' of undefined
at Object.exports.bundle (/Users/jackfranklin/.nvm/v0.10.36/lib/node_modules/jspm/lib/bundle.js:82:31)
```
Took me a moment to figure it out so thought I'd update so it warns instead. Let me know what you think!

Add a warning when bundle is called with no arguments

---

lib/config/loader.js
lib/config/package.js
lib/config/utils.js
test/loader-utils.js

Since [naming conventions](https://docs.npmjs.com/files/package.json) on npm packages says, that `Any name with non-url-safe characters will be rejected. Also, it can't start with a dot or an underscore.` it would be logical to prefix private fields with `_` so they will not be filtered by `extractObj`.

Prefix private fields with __

---

lib/build.js

This happens, when `subDir` is equal `.` - seems like node does not handle path with dot on end well.

Fix EINVAL rename error

---

.editorconfig
.gitignore
.jshintignore
.jshintrc
api.js
cli.js
lib/build.js
lib/bundle.js
lib/common.js
lib/config.js
lib/config/loader.js
lib/config/package-name.js
lib/config/package.js
lib/config/utils.js
lib/core.js
lib/endpoint.js
lib/global-config.js
lib/install.js
lib/link.js
lib/package.js
lib/semver.js
lib/ui.js
package.json
test/.jshintrc
test/api.js
test/package.js

- Added jshint linter to `npm test`
- Added editorconfig
- Minor code refactoring as discussed in https://github.com/jspm/jspm-cli/commit/3d3fb0b47c6f8850c6cad3834e274cc2a51364a9#commitcomment-9734519
So far everything works as expected and I hope that I didn't introduce due to the many changes some unwanted bugs. Most of the linter warnings have been of type `==` vs `===` or missing `;` at the end of the lines. The diff shows also many modified lines due to trimming of trailing whitespaces.
Futhermore I'd recommend to active `qurly` so that each block or scope requires `{}` to avoid easy to overlook typos like:
```javascript
if (Error)
console.log('Error');
return Error;
// If no error continue here ...
```
To avoid annoying build errors after pusing your code to the upstream because of …

added jshint linter and editorconfig

---

README.md

It's quite impressive that jspm has already 14k downloads per month :)
A preview of the badges you can find here https://github.com/subesokun/jspm-cli/tree/chore-badges

added npm version and npm downloads badges

---

CONTRIBUTORS

I've included all contributors to the project from the git commit history. If you do not want to be included please let me know.
@subesokun @benib your real names were not specified in your git commits so you have not been included. Let me know these details if you'd like to be added.
Thanks for supporting the project!
@crisptrutski @djindjic @floatdrop @subesokun @tauren @douglasduteil @jimthedev @computmaxer @Bubblyworld @suyash @bennage @trusktr @markstickley @probins @yeban @Jarreddebeer @jamespamplin @lindseydew @jackfranklin @toranb @duy-n @tkellen @benib @theefer @speigg @dropout @davidblurton

Add Contributors

---

cli.js

typo caused `jspm registry export [name]` to fail with an exception.

fixed typo in registry export

---

lib/semver.js
test/semver.js

Fix ^ and ~ range matches on x.y patterns

---

package.json

Enforce semver to a version 4.3.2 or greater for security reason.
see [semver Regular Expression Denial of Service](https://nodesecurity.io/advisories/semver_redos)

fix(dep): semver security vulnerability

---

cli.js
lib/install.js

Refs #640 
```
jspm install jquery@1.7 # installs 1.7.2
jspm update jquery      # installs 2.1.3
```
```
jspm install jquery@1.7 # installs 1.7.2
jspm update jquery      # installs 1.11.2 (which matches 1.7 in packages.json)
jspm install jquery     # installs 2.1.3
```

Read existing ranges for `jspm update x`

---

lib/package.js
test/package.js

@guybedford let me know if this fits your idea of how prereleases should interact with the `stable` flag

Support "stable" prereleases

---

lib/config.js

Fixes https://github.com/jspm/jspm-cli/issues/677 but without solving the migration problem.
A more correct cross-platform solution would be to have config.js expose multiple environment variables for correct paths depending on content.
The `.` prefix on Windows doesn't serve any purpose and can be removed, but this would require a larger refactor to have OS specific directory names.
A quick search (https://github.com/jspm/jspm-cli/search?utf8=%E2%9C%93&q=config+home&type=Code) suggests that the only thing HOME is used for is the .jspm folder so perhaps config.js could instead expose the JSPM cache/settings folder (name TBD) which could then be named more appropriately on Windows vs *nix.

Changes HOME on Windows to %LOCALAPPDATA%.

---

lib/package.js
test/package.js

Two ways to say "guess" are probably enough.
@guybedford decided not to simplify any of the other behaviour - all makes sense to me at least.
Refs #694

Remove magic meaning of "true" dependency.

---

lib/install.js

Refines #667 
Alternately, you may not want to support explicit versions in `update`

Disallow version in `jspm update x@version`

---

lib/package.js
test/package.js

Refs jspm/npm#34
@guybedford so github and npm endpoints would be updated to return things like `{versions: [...], latest: 'master'}`
Passing in `options`, rather than `latestVersion` directly, to anticipate `--edge` option.

Support convention of "latest" version

---

cli.js

Shoudl fix #783, I just made the option `--inline-source-maps` instead of `--inline-source-map`, mind the trailing *s*.
@crisptrutski , please give it a look.

Fix #783, added --inline-source-maps in in bundle and bundle-sfx command

---

lib/common.js
lib/config.js
lib/config/loader.js

Currently, when the config file is written meta information is output before map. If you set meta information for installed libraries, e.g. adding jQuery as dependency for Angular, the meta entry for would not be normalized properly and thus would not have any effect. This change writes the meta config at the end of the SystemJS configuration.

Set meta information at the end so that entries get normalized properly

---

cli.js
lib/ui.js

This PR adds four new log levels, customised with the `--log` flag.
- `--log debug` (default) everything is logged
- `--log info` info, warnings and errors are logged ('ok' is excluded)
- `--log warn` warnings and errors are logged
- `--log err` only errors are logged
@guybedford I finally found some time to look at #528 and this is my first stab. What do you think?

Include the ability to customise log levels

---

cli.js

This allows the user to configure that they'd like `sourcesContent`
included in the sourcemap created by jspm.
Closes https://github.com/systemjs/builder/issues/298.
@guybedford can you take a look please? Thanks for your help.

Add --source-map-contents option to `jspm bundle`

---

api.js
test/api.js

Couple of times I've written small tools in which I've wanted to just
log the current version of jspm.
@guybedford seemed like a sensible addition to me - what do you think?

Expose the jspm version in the API

---

cli.js

I can't do conditionally drop code while doing minify bundle via JSPM CLI, which SystemJsBuilder original supported.  
See  
https://github.com/systemjs/builder/blob/master/lib/output.js#L82
at line: 82  
ast = ast.transform(uglify.Compressor({
dead_code: true,
global_defs: globalDefs,
warnings: false
}));
So I added this missing part to JSPM.
Adds uglify's dead_code and global definition support to CLI for consistency with SystemJS builder.

Adds uglify's dead_code&global_defs support for consistency with SystemJSBuilder.

---

package.json
test/pjson.js

Files generated by tests contain Windows-style line endings which fail assert equal tests.  These should either be normalized at write or within the unit tests.
Also changed license format so npm doesn't complain.

Tests fail under windows (CRLF != LF)

---

lib/package.js

One custom step need is to add `packages: { "myModule": { defaultExtension: "{myExtension, e.g. ts}" } }`, which is ok to do before 0.17

Add support of non '.js' main

---

cli.js

This means that any script run with `jspm run` will get the regular
`process.argv`, and all args given to `jspm run` will make it through to
the target script. Closes #1305.

Avoid mutating process.argv

---

cli.js
lib/install.js

Closes #1297.
@guybedford I'm not sure if it's as simple as this - but a quick test showed that this works fine for the base case. I feel like I might have missed something though.

Add `--production` flag to not install dev dependencies.

---

lib/global-config.js
package.json
test/fixtures/global-config/.jspm/config
test/fixtures/global-config/expected/combined.json
test/fixtures/global-config/expected/default.json
test/global-config.js

This pull request should solve issues file locking issues raised in #1198 and #1076.
Basically, I rearranged the global-config.js file to do this, in order:
1) lock ~/.jspm/config
2) read ~/.jspm/config
3) apply the defaults/migrations with `dprepend`
4) save the config _only_ if it is different from the file on disk.
5) unlock the file
This allows multiple jspm processes to start/run concurrently, without accidentally overwriting the global config when another process is writing to it.

Add file locking for global config

---

cli.js
lib/global-config.js
test/global-config.js

One more small code change for your review. Right now, `jspm config strictSSL false` will set the value of the `strictSSL` key in `~/.jspm/config` to string `"false"`, instead of boolean false. Same for integers (eg registries.github.maxRepoSize).
This code change will read "true" and "false" from the command line and convert them to booleans, and convert strings of numbers to integers.

Allow boolean and integer types with jspm config CLI

---

docs/installing-packages.md

The only example of the cli override syntax I know if is found in a sub doc page of the jspm/registry: 
https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#testing-configuration

Simple override example

---

lib/package.js

Use `package.son` format if defined in createMain()

---

api.js

I am developing an autoinstaller plugin for systemjs-builder and was faced by the need to do local linking during development by using the module api. Just added a new function export `link(...)` and delegated to `lib/link.link(...)` .

Allow linking through module api

---

lib/link.js

See https://github.com/jspm/jspm-cli/issues/1450

When linking use `*` as pkg name format by default

---

lib/package.js

There might be a preference for a better error message, but that error condition should be nearly non existant. Only case is if a user deletes the linked package.json after sometime and then relinks the package.

Find linked package root to read package.json, fixes #1462

---

lib/package.js

Sorry about this. To satisfy the JSHint run on the CI I needed to move the function declaration to the top level and thought I had caught adding `pkg` for the error message. However I missed the recursive call and when I tried again today linking was infinite looping.

Fix bug creeped satisfying JSHint top level functions

---

cli.js

I'm constantly mistyping `jspm install` as `jspm isntall`. This PR allows JSPM to work when the typo is typed.

Make install typo isntall work

---

lib/config/config-file.js

Multiline regexes match on both CR and LF, causing tabSpaces to alternate between actual lines and blank lines, messing up detection. (I commonly got 6 or 10 spaced config files...not fun.)
A fix is to split by the detected line ending and then match on every line (with single line regex)
Ideally it'd be nice to find a regex that just works for both types, but I couldn't see how js global regexes capture groups (i.e. you'd match on the full line but only capture spaces at start)

0.17 beta - Fix tab detection on windows/CRLF line-endings

---

lib/config/index.js

Got a little confused when upgrading to 0.17, as there was no file named `jspm.js`. I'm assuming this should read `jspm.config.js`.

0.17: Change "jspm.js" to "jspm.config.js" in upgrade notes

---

cli.js

Alternatively this and skip-rollup could be moved to not even need an if statement (similar to `no-mangle`), which looks a little cleaner

Fix skip encode names

---

lib/bundle.js

I noticed my CI builds were completing even though the build had an error, this should fix it.
The error thrown here is caught up the pipeline in cli.js where it correctly `process.exit(1)`'s.

Fix build errors not exiting with 1

---

lib/bundle.js

Really cool to see the new file watching in `0.17` @guybedford , excellent job on this lib.
Small fix: I noticed that the `buildWatch` fn sometimes selects the lowest directory incorrectly.  It now loops through the entire module tree and as a result some `jspm_packages` can resolve as "lower" than the main application code.  Sorting the files by their length first  then selecting the shortest directory seems to fix it. 
LMK what you think. Happy to help debug/test further.

File watching: Use sort to select the lowest directory for `buildWatch`

---

cli.js
lib/bundle.js
lib/cli-utils.js
test/cli-utils.js

This PR provides support for `jspm install lib -o directories.lib=asdf dependencies.jquery=*` style override syntax, and all other object flags.
This also includes support for an `--externals` flag which is passed to SystemJS Builder (effectively equivalent to `jspm build x --config meta.external.build=false`).
Finally, when using global deps (`jspm build test.js --global-deps jquery=$`), these are now automatically treated as externals.
Together, these give much nicer workflows around builds and installs.

Option assignment syntax

---

lib/registry.js

If a timeout occurs during the build, the warning message incorrectly directs the user to increase the `lookup` timeout:
warn Timed out on build
To increase the timeout run jspm config registries.npm.timeouts.lookup 240
This commit corrects the message to show the `registries.npm.timeouts.build` property instead.

Correct the warning message for `build` timeouts

---

.appveyor.yml

Hi @guybedford 
Going through the [the lastest npm version changelog](https://github.com/npm/npm/releases/tag/v3.9.0), I discovered [AppVeyor](https://ci.appveyor.com).
It's yet another CI but this one is running on Windows :rabbit: 
So I made a [little study](https://github.com/douglasduteil/study-test-es6-universal-lib/pull/1) to propose testing the jspm CLI on a native Windows environnement.
Because Windows users need some love too ;)

chore(appveyor): test cli on Windows

---

lib/config/index.js

- fixed the initialization of typescript projects by loading .ts files into plugin-typescipt instead of *.js files. This eventually resulted in the `err  Source StudioDashboard/App.js has multiple anonymous System.register calls.` error when trying to bundle or build (fixes #1859).
- If the user inputs a typescipt file for the main entry point the 'Select a transpiler' step will default to 'typescript' instead of 'babel'
Note: I tried to match your coding style, making it as terse as possible. Tell me if there is anything wrong with it. Thanks!

[0.17.0-beta-17] Fixed typescipt support for `jspm init` (fixes #1859)

---

lib/bundle.js

This change means you can install a package and not have your watch task
bail on you.
My thoughts here are to keep an eye out for when the config file changes (when you do an install for example) and then refresh the builder instance such that it loads the new config in.
However doing so in the manner I've got in the code leads to the `bundle` failing with:
```
err  Error: Configuration file jspm.config.js has been modified by another process.
```
Which I completely understand. I'm not sure then if this is straightforward as I think, or if actually I'm just going about it in the whole way - my lack of knowledge of the internals of SystemJS Builder might be holding me back.
@guybedford have you any thoughts?

`--watch` deals with the configuration changing.

---

lib/install.js

Currently, this only shows top level dependencies.
This commit allows to show all the forks and what their parent
packages are.
This was previously discussed in PR #1968 as a new feature,
while it was actually a bug.
Example output:
Installed versions of npm:d3
d3 4.1.1 (^4.1.1)
npm:d3-heatmap@1.2.1
d3 3.5.17 (^3.5.16)

Fix the jspm inspect registry:name when there are forks

---

cli.js
lib/core.js

similar to my other PRs 🔸 
also happened to once again catch in a CI build.
the direct .catch is for errors in system.import (e.g. file not found, or the module throws on loading) and the uncaughtException exit is for any other error.

fix jspm run not exiting with code 1 after error

---

lib/config/index.js

This resolves #2110 by making the following changes to the `init` command
1. Include `"defaultExtension": "ts"` in local package config when the `transpiler` is inferred to be TypeScript. For example this will now happen when the local package main is specified as `app.ts`.
2. Inferring TypeScript as the transpiler when the local package package main has a `.tsx` extension, as should be the case for TypeScript React projects. In this case add `"defaultExtension": "tsx"` to local package config.

Improve init defaults for TypeScript projects

---

lib/config/package.js
lib/install.js

Part of https://github.com/jspm/jspm-cli/issues/1899
I went with the simplest solution of just executing a hook script with no arguments.
@guybedford Could you have a look at this and tell me, if it is alright. If so I will add a `preinstall` hook [here](https://github.com/jspm/jspm-cli/blob/master/lib/install.js#L88).

feat(hooks): add postinstall and preinstall hook support

---

lib/core.js

The code emit changes between these major versions all expand TypeScript's support for transpiling ES2015 syntax. A few involve better SystemJS support and I think this upgrade will be beneficial overall. That said, I primarily use TypeScript via plugin-typescript.
This would resolve #2145

update typescript option to install latest stable

---

cli.js
lib/install.js

See #1977. The `--exact` flag is intended to be similar to npm's [save-exact](https://docs.npmjs.com/cli/install) flag, where you don't have to specify the version but it still pins the dependency to the latest version.
I saw that you put the discussion label on #1977 and am not sure if that means there was more to talk about before creating a pull request -- if so let me know.

Implement #1977: --exact flag for pinning latest version of dependency

---

lib/config/package.js

`depsPrefixed` is not set correctly, if no `package.json` exists.
Set `depsBase` has no effect because the value is going to be overridden based on the `depsPrefixed` value when writing the file.

fix setting of jspm and deps prefix

---

lib/link.js

[jspm link relative path on a Windows environment #2198](https://github.com/jspm/jspm-cli/issues/2198)

regarding issue #2198

---

lib/config/index.js

This quick fix allows transpilation to be available with bundling when package.json is not found in the same directory.
To add a little bit of context, I am copying all source files (including jspm config files) in a temporary folder where I am doing some post-process with them (adding CDN path, etc...).
I was able to call `jspm build ...` (cwd the temp folder) to bundle with `Rollup` correctly, but transpilation was only possible if package.json was there. (my bundle was containing es2015 features and I want to support older browser). This is the same issue for `jspm bundle ...`.
**I temporary fixed it by copying `package.json` into that temp folder, but as we already have the transpiler information within the jspm config file.**
@guybedford : let me know if you think there is another …

[0.17] Allow to use transpiler in bundle if there is no package.json in a temp folder

---

cli.js

Based on https://github.com/jspm/jspm-cli/issues/2174 and on my own experience running into the same incompatibility, I think it would be beneficial to provide a warning when combining the `--format esm` and `--minify` options to the build command until the SystemJS Builder is enhanced to use Babili for minification (https://github.com/systemjs/builder/issues/726).

build: Explain incompatibility between --format esm and --minify

---

cli.js

fix typo in help instructions of cli

fix: Fix cli help typo for 0.17

---

lib/config/global-config.js

If `JSPM_GLOBAL_PATH` points to a directory that doesn't exist, jspm should create that directory.

use mkdirp to create global config path

---

lib/install.js

When running
```shell
$jspm inspect registry:depname
```
where depname is mapped in a configuration file but is not a dependency in `package.json`, an error is thrown by the `showInstallGraph` method. This happens because the `range` argument is `undefined` under these circumstances.
This happens after the warning is correctly printed, but is distracting, making the warning itself easy to miss.
This fix falls back to using the value of `resolved.version` which is likely not ideal behavior either.
Perhaps we should print `'unspecified'` or something of the sort.

fix: showInstallGraph fails if a config is missing from package.json

---

docs/production-workflows.md

Added a warning that module names exist in URL space, so should be / separated. In reference to systemjs/builder#814.

Added warning that module names exist in URL space

---

src/map/index.ts

```shell
$ jspm map ./test.js
```
will fail with :
```
err  TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at new MapResolver ([...]/node_modules/jspm/lib/map/index.js:221:40)
at Object.filterMap ([...]/node_modules/jspm/lib/map/index.js:323:24)
at cliHandler ([...]/node_modules/jspm/lib/cli.js:309:41)
```
`package.json` :
```json
{
"name": "app",
"dependencies": {
"lodash": "^4.17.11"
},
"devDependencies": {
"@jspm/core": "^1.0.4"
},
"type": "module"
}
```
`test.js` :
```javascript
import clone from "lodash/clone.js";
console.log(clone({ a: 'b' }));
```

Fix mapping with no scoped packages

---

.travis.yml
src/install/bin.ts

This fixes the MacOS support for the unix bin file which was using `realpath` which isn't supported on Mac by default. This updates the implementation to use `readlink` instead.
Resolves https://github.com/jspm/jspm-cli/issues/2460 and should actually get the website beta guide running on Mac!

Fix unix bin

---

src/build/index.ts

An other issue with Rollup output (as #2468).
If my external deps share common code, Rollup will create a chunk with this shared code. That's OK.
But Rollup will add this chunk at the output so import map will be wrong again :
```
{
"imports": {
"@etdsolutions/request": "./chunk-e62c8060.js",
"single-spa": "./request-627619e8.js",
"@etdsolutions/stacks": "./single-spa-2080b5a8.js",
"@etdsolutions/uid": "./stacks-ff183556.js",
"@fortawesome/free-solid-svg-icons/faChevronUp.js": "./uid-203f014d.js",
"@fortawesome/free-solid-svg-icons/faChevronDown.js": "./faChevronUp-0ffe90b6.js",
"bootstrap.native": "./faChevronDown-577c640c.js",
"@fortawesome/fontawesome-svg-core": "./bootstrap-c17f3a72.js",
"@etdsolutions/routie": "./fontawesome-svg-core-00332bf4.js",
"one": "./routie-ad357c93.js", …
```

Make sure rollup output matching input

---

src/build/index.ts

This fixes the Array check, which was something between an `instanceof` and `Array.isArray` check.
Fixes https://github.com/jspm/jspm-cli/pull/2480#issuecomment-505789565.

build: fix array instance check

---

package.json

Transitive dependencies do not work well with package managers that do not flatten modules (i.e. pnpm)

Add mkdirp as explicit dependency in package.json

---

src/map/common.ts
src/map/index.ts
src/map/utils.ts

This updates the scope handling in jspm to match the latest SystemJS 5.0.0 and es-module-shims in treating scopes as base-relative instead of scope-relative in the import maps.

Handle scope normalization as base-relative

---

src/cli.ts
src/project.ts

This attempts a new sort of spin on the Yarn workspaces concept.
Currently `jspm install x -p ./project/path` can be used to run a jspm command from a project that is not the current `cwd`.
So the idea is quite simple - _allow the `-p` flag to accept multiple projects, and that way we can operate on many projects at once, effectively getting the monorepo tools out of a simple primitive_.
For example, consider having `packages/[pkgname]` containing a bunch of packages in a monorepo pattern. Then the following workflows would apply:
1. `jspm install -p packages/*` would install dependencies in all packages.
2. `jspm publish -p packages/*` would publish all packages. Some kind of publish flag to only publish new versions could be used to get a proper monorepo workflow out of this.
3. `jspm …

Support multi-project commands
