cli.js
I have added the aliases to the command line, but I am unable to figure out how to add them to the help menu, should I do something like
```shell
...
jspm i -> jspm install
jspm install
...
```
or at the end just give a menu
```shell
...
aliases:
i -> install
...
```
That is the main reason I didn't create a PR in the first place
=> Add aliases to cli.js

api.js
This is useful to call from build tools.
=> Add bundleSFX to API

lib/bundle.js, package.json
Obviously this is pending the release :electric_plug:
=> Upgrade to Builder 0.8.0

lib/bundle.js
Fixes #537. Tested in testlib w/ `jspm bundle-sfx main build.js`
=> Remove config.save from bundlesfx to be nice to watchers

cli.js, lib/ui.js, package.json
This will clear things a little.
=> Use chalk for ansi-colors

api.js
Remove unnecessary `apply` calls.
=> Use direct calls in api.js

cli.js, lib/build.js, lib/common.js, lib/config.js, lib/config/utils.js, lib/install.js, lib/package.js, lib/semver.js, package.json
Since upcoming releases of node will support this methods we could use them now with shim and remove shim later.
=> Use startsWith and endsWith from es6-shim

lib/common.js
It leaked from https://github.com/jspm/jspm-cli/pull/571.
=> Remove strip-bom TODO from common.js

cli.js, lib/core.js
Added command to clear the (global) jspm cache to free disc space.
Fixup for the PR #594
=> added jspm cache-clear command

lib/core.js, package.json
* Update ESML and SystemJS to latest
* Update transpilers to latest
* Automatically update to Babel 5 on loader update 
(this will also cover future updates to both transpilers)
=> Automatic transpiler updates

lib/package.js, test/package.js
Essentially: release > prerelease > master > other
Refs #493
=> When resolving latest, favour prerelease to master

lib/build.js, lib/install.js
Refs #557 
@guybedford hopefully the scariness is contained. Would really like to test this before release (tested manually in dummy project at least).
Also, what are "soft links" like on windows? Can node tell them apart?
=> Enable deletion of entire symlink (but not contents)

api.js
Just like its CLI counterpart: `jspm unbundle`
=> Add `API.unbundle`

lib/registry.js
=> Explictly mark retriable errors

lib/global-config.js, lib/registry.js
=> Strict ssl

lib/package.js, lib/semver.js, test/package.js
=> Relax version range with respect to prereleases in --edge mode

lib/install.js
=> JSPM Install should install devDependencies

lib/registry.js
=> Remove registry config auto saving

lib/install.js, lib/package.js, lib/registry.js, test/package.js
Refs #753
Addresses unexpected behaviour mentioned in comment
=> Revise precedence of `latest` when installing `edge`

lib/common.js, lib/config.js, lib/install.js
=> Recursive clean-up on uninstalls

README.md
note three workflows are defined below mentioning two
=> typo lists three workflows

docs/registries.md
Found a couple of broken links in registries.md. Wasn't sure about the one that pointed to community projects, but the site with third-party resources was the best match I could find.
=> update broken links in registries.md

lib/config/package-name.js
To tackle #1274.
Not entirely sure how to write a test, so I didn't, but let me know @guybedford !
=> Downcase `name` and `target` inputs to jspm.install

lib/config/loader.js
=> Set transpiler to false not 'none' if none set

.gitignore, docs/README.md, docs/SUMMARY.md, docs/build.sh
The book looks like this: http://blog.alex-rudenko.com/jspm-cli/index.html
What do you think?  Would be great to put it on jspm's website and have everything published as a book (maybe, together with systemjs, builder, jspm). Or did you have other plans for documentation in mind?
=> Git book for JSPM

README.md
Hi @guybedford, 
we have added the support for projects to Supporter and I have created a new badge for JSPM. You can see how it appears here: https://github.com/60devs/jspm-cli Also you can sign in to your profile and edit the project description or set the project goals.
I would love to hear you feedback.
Thanks!
=> New Support JSPM badge

lib/bundle.js
Otherwise, the file is not invalidated (as it points to a file that
doesn't exist), so the rebuild doesn't do anyting and the build file
is not up to date
=> watch: reconstruct the full file path when calling the watch callback

cli.js
similar to my previous change, log the error but also quit with code 1.
=> If error on init or inspect, exit with error code 1

docs/publishing-packages.md
Ok that should do it. See #1102
=> Made the publish documentation less confusing #1102

lib/global-config.js
Instead of failing hard - just through importing - it might be enough to
=> Fixed importing with non-writeable home- or jspm-folder. Issue #1778.

.travis.yml, README.md, cli.js, lib/core.js
Public access on coverage https://codecov.io/gh/jspm/jspm-cli
=> chore(travis): publish coverage result to codecov

lib/bundle.js
https://github.com/jspm/jspm-cli/issues/1953
=> #1953 watcher - fix indexOf undefined error on sane fallback

docs/getting-started.md
Updated the file to reflect the TypeScript support in CLI tool init command.
=> Getting started init update for newer version

cli.js, jspm.js
See https://github.com/jspm/jspm-cli/issues/2091.
=> Use process.chdir(directory) to set the current working directory.

lib/config/package.js, testlibs/config.js
=> only rewrite package.json if it has changed

docs/getting-started.md
=> docs/getting-started: bundle-sfx has been renamed to build in v0.17

docs/production-workflows.md
=> docs/production-workflows: bundle-sfx has been renamed to build in v0.17

test/api.js, testlibs/config.js, testlibs/package.json
Updates the versions of jQuery used during test installs.
Ref:
https://nvd.nist.gov/vuln/detail/CVE-2015-9251
https://nvd.nist.gov/vuln/detail/CVE-2016-10707
=> Update package used for tests to secure version

src/build/index.ts
=> Make sure the rollup output array is in the same order as input array
